Repository talkpick/talkpick-batch, pull requests merged in 2025-05, with the labels that each got.

#31 Feature/#17 log back 기반 로깅 시스템 구축
  src/main/java/com/likelion/backendplus4/talkpick/batch/common/annotation/logging/EntryExitLog.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/common/annotation/logging/LogJson.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/common/annotation/logging/LogMethodValues.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/common/annotation/logging/TimeTracker.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/common/aop/logging/EntryExitLogAspect.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/common/aop/logging/LogJsonAspect.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/common/aop/logging/LogMethodValuesAspect.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/common/aop/logging/TimeTrackerAspect.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/common/configuration/WebConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/common/configuration/logging/LogbackConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/common/decorator/logging/MdcTaskDecorator.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/common/interceptor/logging/LogInterceptor.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/sample/common/logging/TestLoggingController.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/sample/common/logging/TestLoggingRequest.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/sample/common/logging/TestLoggingService.java
  src/main/resources/application.yml
Labels: enhancement

#36 Chore/#35 gitignore 수정
  .gitignore
Labels: enhancement

#75 📦 Chore: PR 및 이슈 D-Day 관리 Action 추가
  .github/workflows/d-day-labeler.yml
Labels: 개발 방법론, 배포

#77 Feature/#76 색인 정보 제공 포트에 뉴스 요약 추가
  src/main/java/com/likelion/backendplus4/talkpick/batch/index/domain/model/NewsInfo.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/article/infrastructure/jpa/mapper/ArticleEntityMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/sample/index/NewsIndexServiceTestImpl.java
Labels: 기능 개발

#80 Feature/#78 뉴스 요약 및 벡터 필드 추가
  .gitignore
  src/main/java/com/likelion/backendplus4/talkpick/batch/index/domain/model/NewsInfo.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/index/infrastructure/adapter/ElasticsearchNewsInfoAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/index/infrastructure/adapter/document/NewsInfoDocument.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/index/infrastructure/adapter/mapper/NewsInfoDocumentMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/article/infrastructure/jpa/adapter/NewsInfoProviderAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/sample/index/NewsIndexServiceTestImpl.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/sample/index/providerPort/NewsInfoProviderPortSample.java
Labels: 기능 개발

#86 Feature/#85 모니터링 의존성 추가 및 설정 수정
  build.gradle
  src/main/resources/application.yml
Labels: 배포, 기능 개발

#83 Feature/#82 조회수 동기화 배치작업 이전
  build.gradle
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/article/exception/ViewCountInvalidFormatException.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/article/exception/error/ArticleCollectorErrorCode.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/article/infrastructure/collector/support/mapper/AbstractRssMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/article/infrastructure/jpa/entity/ArticleEntity.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/application/port/in/ViewCountSyncUseCase.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/application/port/out/ViewCountSyncJobPort.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/application/service/ViewCountSyncService.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/infrastructure/adapter/ViewCountSyncJobAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/infrastructure/batch/config/NewsViewCountProperties.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/infrastructure/batch/config/ViewCountBatchConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/infrastructure/batch/config/ViewCountItemConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/infrastructure/batch/config/ViewCountStepConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/infrastructure/item/ViewCountDatabaseWriter.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/infrastructure/item/ViewCountItem.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/infrastructure/item/ViewCountProcessor.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/infrastructure/item/ViewCountRedisReader.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/infrastructure/manager/ViewCountBatchManager.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/infrastructure/quartz/config/ViewCountQuartzJobConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/infrastructure/quartz/config/ViewCountQuartzTriggerConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/infrastructure/quartz/executor/ViewCountSyncJobExecutor.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/infrastructure/tasklet/OldDataCleanupTasklet.java
  src/main/java/com/likelion/backendplus4/talkpick/batch/news/viewcount/presentation/controller/ViewCountSyncController.java
  src/main/resources/application.yml
Labels: 기능 개발
